### ISSUE TITLE
Shortcode

### ISSUE THREAD

**Issue by kleinermann** [algoritmika/wish-list-for-woocommerce#1]
Hi, is there a shortcode i can use to show the wishlist inside a page?

**Comment by kleinermann** [comment]
I just figured it out. The plugin automatically creates a page called wish-list with the shortcode of [alg_wc_wl] in it. Thanks.

**Comment by pablo-sg-pacheco** [comment]
Hi, you are right.
It reminds me it should be better documented on readme.txt.
Thanks
