### ISSUE TITLE
Add a counter in the header

### ISSUE THREAD

**Issue by elusivethemes** [algoritmika/wish-list-for-woocommerce#10]
Hi,

Great plugin. Is there any way I can add a counter to my header of how many products have been added to the wishlist ?

Thanks,

Scott

**Comment by pablo-sg-pacheco** [comment]
Hi, thanks! :)

You mean, you want to display how many products have been added to the wish list in anywhere on your site? Or just on the wish list page using the shortcode?

**Comment by elusivethemes** [comment]
Thanks for the fast reply.  Yes i have a cart link in my header which has a little counter next to it showing the amount of products in the cart. It would be awesome if i could do the same with the wishlist.

So answering your question i guess it would be anywhere on the site.

Thanks.

**Comment by pablo-sg-pacheco** [comment]
:)

There is nothing ready for this case.
But this is a good idea. I'm going to develop it for the next version and I'll let you know, ok?

**Comment by elusivethemes** [comment]
Ok great. Thanks :)

**Comment by elusivethemes** [comment]
Hi,

Another thing I was hoping you could help me with is do you know how I can re-fire the javascript after an ajax call ? Im building an ajax product grid and i lose the wishlist icons after an ajax call. Heres a little video showing what i mean : https://monosnap.com/file/4iZIDr7rdKrbWf7srRao9I8Xmqp4Ah

Hope you can help,

Scott.

**Comment by pablo-sg-pacheco** [comment]
Hello,

Hum, i got it.
I think the wishlist buttons should be there but hidden. The only thing missing is to position them.
Can you try to find them through chrome's console? or better, try to resize the browser. It should trigger the position function and they should appear there. Can you try that please?

**Comment by elusivethemes** [comment]
Yes it looks like your right, the code is showing in the inspector, just cant see them on the page, do you think its a z-index issue ?

**Comment by elusivethemes** [comment]
Resizing doesnt bring them back

**Comment by elusivethemes** [comment]
Managed to fix it with the following, thanks for your help :)

`.woocommerce .products .alg-wc-wl-thumb-btn {
    left: 13px!important;
    display: block!important;
}`

**Comment by pablo-sg-pacheco** [comment]
That's Ok.

Are you using the pro or free version? If you are using the Pro version, I think it's not updated with the resizing trigger yet.

Anyway, if it's working so Ok then.
See you

**Comment by elusivethemes** [comment]
Using the free version and recommending it with my themeforest themes that I sell so it should hopefully bring you some pro sales. Hope thats ok.

**Comment by pablo-sg-pacheco** [comment]
Thanks! I really appreciate it!
If you don't mind to give us a good review on wp.org it would be awesome too.

Tell me more about your themeforest themes too

**Comment by elusivethemes** [comment]
Sure. I will do.

I basically sell themes on themeforest and i specialise in woocommerce themes. I used to use the yit wishlist but your one is much cleaner and minimal. Il be using it on all my themes if you don't mind, so all my buyers will use it and possibly upgrade to pro.

The header counter I mentioned would be a great feature :) its the only thing i can think of that would improve it. Great plugin :)

**Comment by pablo-sg-pacheco** [comment]
Thanks!

On the contrary. I think it's going to be good for us too.
I forgot to tell you. I created the **[alg_wc_wl_counter]** shortcode on the 1.2.10 version. It's ready.

What is your link on woothemes?

**Comment by elusivethemes** [comment]
Ah cool, il try and implement it :) you mean themeforest, its :  https://themeforest.net/user/elusivethemes/portfolio

**Comment by elusivethemes** [comment]
My latest one is going live soon, its the one i've used your plugin on : demo.elusivethemes.com/lotus/

**Comment by pablo-sg-pacheco** [comment]
Yes, themeforest.
Thanks for the link. Who knows if we can work together some day :)

Good work!
Love it when it's clean like this. The Wish list fits perfectly.

Can we add a link to your theme, just for example purposes?

**Comment by elusivethemes** [comment]
The new shortcode works great ! any ideas how to make it update live via ajax ?

**Comment by elusivethemes** [comment]
Yes id be up for that for sure :)

Yes of course, can I send you a link to it when it goes live on themeforest ? just incase anyone wants to buy the theme while there looking ;) haha

**Comment by pablo-sg-pacheco** [comment]
Sure! Why not?
Hehe

I'll think about the ajax thing

**Comment by elusivethemes** [comment]
Awesome, thanks.  Il think of a clever way I can encourage my buyers to upgrade to your pro version as well.

**Comment by pablo-sg-pacheco** [comment]
Thanks!

**Comment by elusivethemes** [comment]
Hi,

I just had a thought. Is there a simple way i can pull the wishlisted products using wp_query ?

I want to ditch the standard wishlist page with the table and create something like this instead :)

![screen shot 2017-07-05 at 02 44 21](https://user-images.githubusercontent.com/10211827/27846015-1d04fd9c-612c-11e7-8c51-2861f0823ea3.png)

**Comment by pablo-sg-pacheco** [comment]
Hello ukscotth,

We've updated the free version to 1.3.0 and now it's updating live via Ajax :)
About using wp_query to get the wishlist, it is possible, but it wouldn't be pretty yet.

I think you could use the template file templates\wish-list.php. (If you create a folder on your theme it can be overrided).

So you could check if you are on a specific page to create a different layout

**Comment by elusivethemes** [comment]
Hi,

Excellent work :) will be perfect on my new theme I’m building. Ive attached a screenshot so you can take a look.  If you want to make the plugin even more amazing one feature you might want to consider adding is giving users the option to hide the counter if its on 0.   

Thanks,

Scott.

P.S My other theme is now online on theme forest if you still wanted to link it :) :  http://preview.themeforest.net/item/lotus-modern-minimal-wordpress-woocommerce-theme/full_screen_preview/19767658?ref=elusivethemes <http://preview.themeforest.net/item/lotus-modern-minimal-wordpress-woocommerce-theme/full_screen_preview/19767658?ref=elusivethemes>

**Comment by pablo-sg-pacheco** [comment]
:) Thanks!

Ok, good idea

We've talked internally about linking to your theme and this idea was not approved. I'm sorry :(
But I still think it could work though.

See you

**Comment by elusivethemes** [comment]
Hey,

Ok no problem, thanks anyway.  Have you got a function to link to the wishlist page ? such as this one that links to the woo commerce cart.

<?php echo wc_get_cart_url(); ?>

Thanks,

Scott.

**Comment by pablo-sg-pacheco** [comment]
Hello, sorry for the delay.

You can do like this:

```
$page_id = Alg_WC_Wish_List_Page::get_wish_list_page_id();
$url = get_permalink($page_id);
```

**Comment by elusivethemes** [comment]
Awesome, thanks :)

**Comment by elusivethemes** [comment]
Hi,

Sorry to be a pain but this seems to of stopped working, is it because of an update ?

Thanks,

Scott.

**Comment by pablo-sg-pacheco** [comment]
Hi,
Not a problem at all.

What stopped working exactly?

**Comment by elusivethemes** [comment]
Thanks for the fast reply.  The code you gave me to display the wishlist link :

$page_id = Alg_WC_Wish_List_Page::get_wish_list_page_id();
$url = get_permalink($page_id);

**Comment by pablo-sg-pacheco** [comment]
Can you confirm if there is a wish list page registered on admin settings ?

**Comment by elusivethemes** [comment]
Oops that was the reason,  sorry for wasting your time lol.

many thanks.

**Comment by pablo-sg-pacheco** [comment]
No prob ;)

**Comment by elusivethemes** [comment]
Hey,

Hope your good.  Ive run into a little problem and was hoping you could help,  the wishlist plugin seems to be conflicting with an image flipper plugin I’m using ( shows secondary product image on hover on archive pages  ) even though i have the wishlist disabled for the archive pages, any ideas how I can fix it ? not sure if its because the wishlist is changing the html structure on the archive pages or something like that.  I only want to use the wishlist on the single product pages on this theme so if theres a way i can stop it completely on the archive pages that would be perfect. 

 Heres a little video showing the problem :

https://monosnap.com/file/wf73zapTP2M5ePoOvXOguhxlqSN2Og <https://monosnap.com/file/wf73zapTP2M5ePoOvXOguhxlqSN2Og>

Many thanks,

Scott.

**Comment by pablo-sg-pacheco** [comment]
Hello,
I'm fine, what's up?

Can you please create this particular issue on github? I'll take a look on it better when I have some time.
Give me that image flipper name too, and the site url if possible

See you

**Comment by elusivethemes** [comment]
Hey,

Sure. Il do that now. Thanks :)

Scott.

**Comment by elusivethemes** [comment]
Hey,

I’m using your variations plugin now aswell which is great :

Is there any way to show the variations on the products on product archive pages ?

Im trying to achieve this kind of thing :



Cheers,

Scott
