### ISSUE TITLE
Wish list for WooCommerce pro adding incorrect items

### ISSUE THREAD

**Issue by ericesch** [algoritmika/wish-list-for-woocommerce#20]
I ha e the pro version on my company woocommerce website. I have a customer that sent me screen shots of it placing random other items we sell into her wishlist when she is trying to place a specific one on her list. I havent had any other customers mention this, my dummy account seems to be working fine from both my cell phone and my windows laptop. Customer is on a windows laptop.

**Comment by ericesch** [comment]
Added here because your developer@thankstoit.com inbox is full.

**Comment by pablo-sg-pacheco** [comment]
Hi @ericesch ,
Please try the support@thankstoit.com address.
I just wiped it and it should work.

Would it be possible for you to create/share an admin account to your server (WP and preferably FTP), so I could login and check what's going on?

**Comment by ericesch** [comment]
I sent you an email with a admin login to our website pandadips.com.
attached is your ftp log in info. The customer having issues is
terisemail. I have not had any other customers report issues.

Attached is also her screen shots of the issue.

**Comment by pablo-sg-pacheco** [comment]
I received the login email from WordPress but couldn't access the ftp nor the screenshots.
Can you please try again and send it to support@thankstoit.com one more time?

**Comment by pablo-sg-pacheco** [comment]
I'll close it as it seems the issue has been fixed, but if you notice anything else let me know ;)
